export enum InventoryActionTypes {
  GET_INVENTORIES = "GET_INVENTORIES",
  GET_INVENTORIES_SUCCESS = "GET_INVENTORIES_SUCCESS",
  GET_INVENTORIES_FAILURE = "GET_INVENTORIES_FAILURE",
  CREATE_INVENTORY = "CREATE_INVENTORY",
  CREATE_INVENTORY_SUCCESS = "CREATE_INVENTORY_SUCCESS",
  CREATE_INVENTORY_FAILURE = "CREATE_INVENTORY_FAILURE",
  UPDATE_INVENTORY = "UPDATE_INVENTORY",
  UPDATE_INVENTORY_SUCCESS = "UPDATE_INVENTORY_SUCCESS",
  UPDATE_INVENTORY_FAILURE = "UPDATE_INVENTORY_FAILURE",
  DELETE_INVENTORY = "DELETE_INVENTORY",
  DELETE_INVENTORY_SUCCESS = "DELETE_INVENTORY_SUCCESS",
  DELETE_INVENTORY_FAILURE = "DELETE_INVENTORY_FAILURE",
}
